### ISSUE TITLE
New Card Design

### ISSUE THREAD

**Issue by michellzappa** [envisioning/readiness.io#80]
- Card opens when a technology is clicked on Map Layer
- Existing right-hand Card Sidebar should be removed
- Replace with hovering Card, displayed on top of Map Layer

Example:
![img_20160113_160032222](https://cloud.githubusercontent.com/assets/5923523/12333115/7d5cfa5a-bad9-11e5-86c0-f78280be97a5.jpg)

**Comment by arthursoares** [comment]
This was replaced by #85.
