### ISSUE TITLE
Bug: Change Order

### ISSUE THREAD

**Issue by michellzappa** [envisioning/readiness.io#82]
When you change Order (left sidebar) from Category to Name to Category, the actual order of Technologies gets jumbled.

<img width="502" alt="screenshot 2016-01-14 16 38 56" src="https://cloud.githubusercontent.com/assets/5923523/12333763/50383a9a-badd-11e5-86d2-17356dfb2c7d.png">

**Comment by arthursoares** [comment]
I think I was the one that broke it. Let me take a look.
